### ISSUE TITLE
Clean Up Default Next.js Web App

### ISSUE THREAD

**Issue by mantuok** [sfbrigade/datasci-earthquake#41]
## Context
The default Next.js 13 setup contains unnecessary files and configurations. We need to clean up the project structure to focus on our application development. Additionally, we should integrate Prettier as a code formatter to ensure consistent visual styling throughout the codebase. It's essential to make sure that Prettier does not conflict with ESLint.

## Definition of Done
1. Remove unused files, components, and styles.
2. Ensure the project builds and runs error-free.
3. Prettier is installed and integrated
4. There is no conflict between ESlind and Prettier.

## Engineering Details
Delete default files, unused CSS, and other starter components. Verify the app
- builds with npm run build
- runs locally with npm next-dev
- ESLint starts analyzing with npm run lint
- eslint-config-prettier installed to disable conflicting rules

**Comment by mackcooper1408** [comment]
looks great! how big of a task do you think this is? I only ask because maybe you can toss in a few extra minor config pieces. namely:
1. let's run `npm run lint` which should give generate an eslint config file.
2. let's decide on/install a formatter (prettier perhaps?) then add a script to run that in the package.json

also I want to configure some pre-commit hooks so that all the linting and formatting is automatically done/checked... but I'll probably slide that into a separate issue
